### ISSUE TITLE
Can't boot system after archzfs upgrade to 0.7-git

### ISSUE THREAD

**Issue by colorprint** [archzfs/archzfs#76]
I have arch linux installed on ZFS and booted from it.
After update to 0.7 last night I am not able to boot the system:
ash: 1 unknown operand
importing pool vault
running late hook [zfs]
no pools available to import
ERROR: Failed to mount the real root device
rootfs#

In rootfs command prompt I can see that vault pool was imported.

Also I have the bootloader entry below (no any changes, worked fine before):

title    Arch Linux
linux    /vmlinuz-linux
initrd    /intel-ucode.img
initrd    /initramfs-linux.img
options   zfs=vault/ROOT/default rw

**Comment by lnicola** [comment]
Possibly a different bug, but I'm getting a `Can't mount pool/fs to /new_root/pool/fs due to canonicalization error 2` message. Running `zfs mount` in the emergency shell seems to mount it, but I don't know how to continue with the boot.

I was running `zfs-linux-git`, so this seems to be caused by yesterday's updates.

**Comment by colorprint** [comment]
Yes, and after reverting back to 0.6 it works again...

**Comment by csachs** [comment]
Ah, more people with this (?) problem. I get the same error message like @lnicola .

To manually continue boot, I've used [my pool is named pool, my archlinux root is pool/os/arch/root] the following comamnds at the emergency shell. (The last one is the one which will continue the boot…)
```bash
zpool export pool
zpool import pool
mount -o bind /pool/os/arch/root /new_root
exec /usr/bin/switch_root /new_root /sbin/init
```

I've put the three lines above in (without the last) in a late `mkinitcpio` hook… not the way to do it, but now at least my system boots again :wink:

The relevant kernel command line part which used to work is:
```
root=zfs zfs=pool/os/arch/root
```

On a more personal note … I know that "lots of complex shell scripts" are the way to do initrd-booting, but I somehow feel, generally, that initrd-scripting has reached some dead-end… hundreds of lines of shell code which easily fail and leave a computer unbootable, while a handful of installation-specific calls would work better. (I've had my fair share of pain with getting two different LUKS drives to unlock before mounting… so I might be biased :wink:).

Regards,
Christian

**Comment by lnicola** [comment]
@demizer Do you have any suggestions for how to make my system boot again?
I mounted my root to `/pool/fs`, then tried `switch_root /pool/fs /sbin/init`, but `systemd` thought I was launching it as a user instance. Adding `--system` got me past that, but then it complained about not wanting to run in a `chroot`.

I've seem https://git.archlinux.org/mkinitcpio.git/tree/init#n54 but I'm not sure what I'm missing.

@csachs Could the `exec` matter in this case?

**Comment by csachs** [comment]
@lnicola Yes try exec, the shell runs as PID 1, by exec'ing, the new child process (first `switch_root`, then `/sbin/init`) 'becomes' new PID 1, and `/sbin/init` must run as PID 1, otherwise it will complain (as you just experienced.)

**Comment by lnicola** [comment]
@csachs Right, that makes sense. I'll try it later and I hope it will also get me past the `chroot` problem.

I believe something `zfs mount /pool/os/arch/root` might be enough. But is there no need to bind-mount `/dev`, `/proc` and `/sys`?

About `initrd` scripts, I think there is an option to start `systemd` directly using the `mkinitcpio` hook. I wonder how stable it is and if it works with ZFS.

**Comment by csachs** [comment]
@lnicola `/dev`, `/proc` and `/sys` are mounted earlier in the `/init` shell script (the one you just posted). `switch_root` moves all the mounts to the appropriate places in the new root (cf. ["switch_root moves already mounted /proc, /dev and /sys to newroot and makes newroot the new root filesystem and starts init process."](http://linux.die.net/man/8/switch_root))
I have not tried `zfs mount`, as no `/pool` existed, I don't know if it would automatically create it.
(Furthermore, I would bind mount the directory to `/new_root`, to follow convention, especially since the `switch_root` man pages mentions something about recursively deleting the old root. Don't know if mis-use might be dangerous.)

Having `systemd` in there sounds like an advancement, I'll try to read about that when I have some time.

**Comment by demizer** [comment]
Can someone having problems with booting give me an example of how the system is configured? Like zfs filesystem, zpool datasets and mount points. Also boot loader. I will make a regression test from this.

The test I made to check boot seems to work fine, although I have not made /var or /usr into different datasets.

**Comment by lnicola** [comment]
I don't have anything fancy, the relevant part is:

```
pool                            mountpoint  /pool                       default
pool/zroot                      mountpoint  /pool/zroot                 default
```

with `bootfs` set to `pool/zroot`. `pool` has `canmount` set to `noauto`, `pool/zroot` has `canmount` set to `on`.

It looks like [mounting](https://github.com/zfsonlinux/zfs/blob/master/cmd/mount_zfs/mount_zfs.c#L441) returned `ENOENT`. In the emergency shell, `/new_root` exists, but not `/new_root/pool`, so it is indeed possible that `pool/zroot` cannot be mounted to `/new_root/pool/zroot`.

**Comment by colorprint** [comment]
I have configured it using this manual: https://ramsdenj.com/2016/06/23/arch-linux-on-zfs-part-2-installation.html  (with UEFI).

**Comment by csachs** [comment]
Situation for me is (some parts omitted):

```
> zfs list 
NAME                        USED  AVAIL  REFER  MOUNTPOINT
pool                        219G   649G    96K  /pool
pool/os                     218G   649G    96K  /pool/os
pool/os/arch                218G   649G    96K  /pool/os/arch
pool/os/arch/root           218G   649G  22.6G  /pool/os/arch/root
pool/os/arch/root/home      195G   649G   195G  legacy
pool/os/ubuntu              634M   649G    96K  /pool/os/ubuntu
pool/os/ubuntu/root         634M   649G   634M  legacy
```

Could it be that the legacy mount (pool/os/arch/root/home) causes trouble? (Googling yields [this bug](https://github.com/zfsonlinux/pkg-zfs/issues/196) but I did not check in detail if the situation in the archzfs script is similar …)
@lnicola Did you manage to boot your system? If not, maybe try the export/import first and bind-mount to /new_root …

**Comment by lnicola** [comment]
@csachs Yes, `exec` did the trick. I should have thought about that :D. And there was no need to bind-mount the root.

Regarding `systemd` in `initramfs`, take a look at dasJ/sd-zfs#1 and the corresponding repository.

**Comment by demizer** [comment]
I fixed some parsing errors in the init scripts with ash. I was using bash syntax instead of ash syntax which causes the hook to blow up. I will be adding tests soon to test these parts of the initscripts. Updated packages have been push to AUR. Thanks!

**Comment by lnicola** [comment]
I remember one harmless `ash` error from a long time ago.

> In the emergency shell, /new_root exists, but not /new_root/pool, so it is indeed possible that pool/zroot cannot be mounted to /new_root/pool/zroot.

Did you find anything related to this?

**Comment by lnicola** [comment]
I'm going to try the packages from your repository. I'm not sure whether they include the fixes, though.

**Comment by demizer** [comment]
@lnicola Your use case is quite simple, but the only difference to that of my tests is the usage of systemd-boot. I am not sure of the stability of systemd-boot with zfs as root. You may be running into issues with the hand off. https://wiki.archlinux.org/index.php/mkinitcpio#HOOKS 

Could you please make sure the zfs modules are loaded in the boot environment, you can stop the boot process with premount, see https://wiki.archlinux.org/index.php/General_troubleshooting#Boot_problems

https://github.com/archzfs/archzfs/blob/master/testing/tests/archzfs-qemu-std-test-00-bootfs/fs.sh#L43

**Comment by lnicola** [comment]
I tested the new packages. I no longer get the `ash` error, but the root still doesn't get mounted.

I've been running `gummiboot`, then `systemd-boot` for a long time with no issues of this kind. I still suspect that the `initramfs` tries to mount the root in a directory that doesn't exist: http://imgur.com/a/cWn0l

**Comment by lnicola** [comment]
Well, after looking at the code, I just ran `zfs set mountpoint=/ bike/zroot` and it's fine now.

**Comment by colorprint** [comment]
The new version works fine for me with mountpoint set to "/" instead of legacy.
Thanks!

**Comment by csachs** [comment]
Setting a mountpoint is fine, but somewhat contradictory to setting the root filesystem via kernel command line, especially if one would want to have multiple OS installed on different filesystems in the same zpool…

**Comment by joeyheads** [comment]
Were there any other solutions/updates to this issue?
I'm running into the same issue, and manually specifying the mountpoint hasn't fixed the problem.
Tried the current Linux LTS kernel, as well as the current zfs-linux + linux 4.8.7 combo, same problem on each.
Might try to downgrade zfs in the meantime.
